CREATE SEQUENCE emp_seq START 1;

CREATE SEQUENCE bus_seq START 1;

CREATE SEQUENCE route_seq START 1;

CREATE SEQUENCE stops_seq START 1;

CREATE SEQUENCE pth_seq START 1;

CREATE SEQUENCE emp_bus_seq START 1;

CREATE SEQUENCE bus_route_seq START 1;

CREATE SEQUENCE emp_roles_seq START 1;