insert into autopark.buses_routes (id, bus_id, route_id)
values (nextval('bus_route_seq'),1, 1),
       (nextval('bus_route_seq'),2, 1),
       (nextval('bus_route_seq'),3, 1),
       (nextval('bus_route_seq'),4, 1),
       (nextval('bus_route_seq'),5, 1),
       (nextval('bus_route_seq'),6, 2),
       (nextval('bus_route_seq'),7, 2),
       (nextval('bus_route_seq'),8, 2),
       (nextval('bus_route_seq'),9, 2),
       (nextval('bus_route_seq'),10, 2),
       (nextval('bus_route_seq'),11, 3),
       (nextval('bus_route_seq'),12, 3),
       (nextval('bus_route_seq'),13, 3),
       (nextval('bus_route_seq'),14, 3),
       (nextval('bus_route_seq'),15, 3),
       (nextval('bus_route_seq'),16, 3),
       (nextval('bus_route_seq'),17, 3);

insert into autopark.employee_buses (id, user_id, bus_id)
values (nextval('emp_bus_seq'),2, 1),
       (nextval('emp_bus_seq'),3, 2),
       (nextval('emp_bus_seq'),4, 3),
       (nextval('emp_bus_seq'),5, 2),
       (nextval('emp_bus_seq'),6, 3),
       (nextval('emp_bus_seq'),7, 3),
       (nextval('emp_bus_seq'),8, 4),
       (nextval('emp_bus_seq'),9, 4),
       (nextval('emp_bus_seq'),10, 5),
       (nextval('emp_bus_seq'),11, 5),
       (nextval('emp_bus_seq'),12, 1),
       (nextval('emp_bus_seq'),13, 1),
       (nextval('emp_bus_seq'),14, 2),
       (nextval('emp_bus_seq'),15, 2),
       (nextval('emp_bus_seq'),16, 3),
       (nextval('emp_bus_seq'),17, 3),
       (nextval('emp_bus_seq'),18, 4),
       (nextval('emp_bus_seq'),19, 4),
       (nextval('emp_bus_seq'),20, 5),
       (nextval('emp_bus_seq'),21, 5);